//page settings
export const ADD_ARTICLE = "ADD_ARTICLE";
export const FOUND_BAD_WORD = "FOUND_BAD_WORD";
export const CHANGE_HEIGHT_PAGE = "CHANGE_HEIGHT_PAGE";
export const SHOW_MATH_EQUATION_TEXT_BOX = "SHOW_MATH_TEXT_BOX";
export const CHANGE_MARKUP_LANGUAGE = "CHANGE_MARKUP_LANGUAGE"
export const CHANGE_MATH_INPUT = "CHANGE_MATH_INPUT"
export const UPDATE_RENDER_CANVAS = "UPDATE_RENDER_CANVAS"
export const UPDATE_BASE64_Math_IMAGE = "UPDATE_BASE64_Math_IMAGE"
export const UPDATE_SVG_MATH_IMAGE = "UPDATE_SVG_MATH_IMAGE"
export const UPDATE_WIDTH_MATH_EQUATION = "UPDATE_WIDTH_MATH_EQUATION"
export const UPDATE_HEIGHT_MATH_EQUATION = "UPDATE_HEIGHT_MATH_EQUATION"
export const UPDATE_POP_UI_PAGE = "UPDATE_POP_UI_PAGE"
export const UPDATE_DOWNLOAD_IMAGE_TYPE = "UPDATE_DOWNLOAD_IMAGE_TYPE"
export const UPDATE_POP_UI_TYPE = "UPDATE_POP_UI_TYPE"
export const UPDATE_MATH_TEXT_COLOR = "UPDATE_MATH_TEXT_COLOR"

//local sync
export const UPDATE_ALL_LOCAL_SYNC_OPTIONS = "UPDATE_ALL_LOCAL_SYNC_OPTIONS"
export const UPDATE_IMAGE_DIMENSIONS_SETTINGS = "UPDATE_IMAGE_DIMENSIONS_SETTINGS"